Ocean,py: datatoken.,verify_order_tx : should allow access if the sender is either the consumer or the payer of an order
oceanprotocol/ocean.py pull request #119
Opened 2021-02-03 16:20 UTC by mariacarmina

Fixes #116  .

Changes proposed in this PR:

- verify_order_tx function should allow access for both roles that a sender can have: consumer or payer

2021-02-04 07:33 UTC, alexcos20 requested changes

2021-02-04 07:33 UTC, alexcos20 commented on ocean_lib/ocean/ocean_assets.py
> +        print("Asset: ", asset)
could we remove this debug logs ?

2021-02-04 07:40 UTC, mariacarmina commented on ocean_lib/ocean/ocean_assets.py
> +        print("Asset: ", asset)
Sure.

2021-02-05 07:14 UTC, alexcos20 approved these changes
lgtm.  @ssallam @calina-c ?

2021-02-05 08:09 UTC, calina-c requested changes
Just a small (and unimportant) suggestion to help with readability.

2021-02-05 08:09 UTC, calina-c commented on ocean_lib/models/data_token.py
> +        if order_log.args.consumer != sender and order_log.args.payer != sender:
to avoid and/or ambiguity, can we make this condition: `if sender not in [order_log.args.consumer, order_log.args.payer]`?

2021-02-05 08:09 UTC, calina-c commented on ocean_lib/models/data_token.py
> +            if order_log.args.consumer == sender or order_log.args.payer == sender:
and we can reuse the same condition (without `not` this time, I think) here.

2021-02-05 10:47 UTC, calina-c approved these changes

2021-02-08 08:06 UTC, calina-c approved these changes

2021-02-08 08:08 UTC, merged