Fix inconsistent versions of python and pip. Remove --pre flag from ocean-lib installation
oceanprotocol/ocean.py pull request #1267
Opened 2023-01-06 20:21 UTC by mariacarmina

Fixes #1266  .

Changes proposed in this PR:

- fix inconsistent versions of python and pip.
- add permissions to `start_ocean.sh`
- remove `--pre` flag from ocean-lib installation

2023-01-06 22:23 UTC, trentmc approved these changes

2023-01-08 12:04 UTC, mariacarmina commented
This issue should not be encountered when creating a python3 venv, because it automatically uses python3 and also the correct version of pip. Let's revert the changes and use everywhere in the READMEs python and pip.
cc @calina-c @trentmc

2023-01-09 07:37 UTC, calina-c requested changes

2023-01-09 07:37 UTC, calina-c commented on READMEs/c2d-flow-more-examples.md
> +`pip3 install Pillow`
please revert changes referencing pip3 and python3. If the venv is activated, the correct version of python will be used.

2023-01-09 07:37 UTC, calina-c commented on READMEs/setup-local.md
> +sudo chmod +x start_ocean.sh
please wrap this in a console or at least `code` markdown. I think the instruction above should be the same

2023-01-09 07:37 UTC, calina-c commented on ocean_lib/ocean/test/test_ocean_assets.py
> +@pytest.mark.skip(reason="Skip this until #1268 is merged.")
@mariacarmina please fix inside this PR. All you need to do is cherry-pick 11ce25f09cf4873055740bf4eff17f49d3628671 and the subsequent changes here: https://github.com/oceanprotocol/ocean.py/pull/1265/files#diff-dfe25f756de0539701ed9f2643a7d93f22dfb4649eac3e4a6d7f0bd0820545c7

2023-01-09 11:39 UTC, calina-c reviewed
Just a small wording change, please.

2023-01-09 11:39 UTC, calina-c commented on READMEs/developers.md
> +#Use python3 to create the env for Python3.8, Python3.9, Pyhton3.10, Python3.11.
there is a typo in Python3.10, also I think you can rephrase as: "make sure your Python version inside the venv is >=3.8."

Can you please add spaces after the `#` character throughout this file? It always bugs me and I don't want to perpetuate this

2023-01-09 11:39 UTC, calina-c commented on READMEs/setup-local.md
> +sudo chmod +x start_ocean.sh
no, sorry. I missed the generic wrap :)

2023-01-09 13:55 UTC, calina-c approved these changes

2023-01-09 15:26 UTC, merged