Replaced Binance API with Kraken example
oceanprotocol/ocean.py pull request #1382
Opened 2023-04-04 13:14 UTC by mariacarmina

Fixes #1375  .

Changes proposed in this PR:

- replaced Binance API with Kraken example.

2023-04-04 14:14 UTC, trentmc requested changes

2023-04-04 19:53 UTC, mariacarmina commented on READMEs/publish-flow-restapi.md
> +The data follows the Kraken docs specs for Data, [here](https://docs.kraken.com/rest/#section/Example-API-Clients).
Thank you, will do.

2023-04-05 00:36 UTC, trentmc commented on READMEs/publish-flow-restapi.md
> +The data follows the Kraken docs specs for Data, [here](https://docs.kraken.com/rest/#section/Example-API-Clients).
It's not done yet. I don't want just "data". I want the closing prices, just like the past example.

2023-04-05 08:10 UTC, mariacarmina commented on READMEs/publish-flow-restapi.md
> +The data follows the Kraken docs specs for Data, [here](https://docs.kraken.com/rest/#section/Example-API-Clients).
Ok, I have also used [ticker information](https://docs.kraken.com/rest/#tag/Market-Data/operation/getTickerInformation) for this just as it was with Binance API.

2023-04-05 10:50 UTC, calina-c approved these changes

2023-04-05 12:58 UTC, trentmc requested changes
I do *not* approve yet.

I want it to grab not just the most recent close price, but the last 500 (or whatever it is). Like Binance did.

Please fix.

2023-04-05 14:27 UTC, mariacarmina commented
The closing prices output after running the README steps:
![Screenshot from 2023-04-05 17-26-58](https://user-images.githubusercontent.com/50501033/230111885-6f00d7a1-cf84-4f53-9497-f7c3a132cc2f.png)

2023-04-05 22:50 UTC, trentmc requested changes
Getting close, good! 

One small tweak requested.

2023-04-05 22:50 UTC, trentmc commented on READMEs/publish-flow-restapi.md
> +close_prices = [float(item[4]) for item in data['result'][pair]]
Replace `item` with `data_at_day`

2023-04-06 12:45 UTC, trentmc approved these changes

2023-04-06 12:46 UTC, merged