Codacy fixes 2nd
oceanprotocol/ocean.py pull request #190
Opened 2021-03-03 15:28 UTC by calina-c

Towards #174.

2021-03-03 15:58 UTC, trentmc commented on ocean_lib/assets/__init__.py
> -#
Why was this deleted? I know that for pytest (and maybe other things) you need an __init__.py file.

2021-03-03 16:09 UTC, trentmc requested changes
The comments give specific suggestions. Big picture: (a) why delete the __init__.py's (I am somewhat certain they are needed for testing) (b) why a bunch of redundant comments like "initialize __" ?

2021-03-03 16:09 UTC, trentmc commented on ocean_lib/ocean/__init__.py
> -#
There are unit tests as subdirectories of this. So I'm pretty sure that this one is needed in order for pytest. (But I could be wrong! Maybe check)

2021-03-03 16:09 UTC, trentmc commented on examples/__init__.py
> +"""Initialises examples package."""
What's with all the "initialize" and "initializes" comments? Redundant because it's obvious imo. Therefore violates DRY

2021-03-03 16:09 UTC, trentmc commented on ocean_lib/web3_internal/web3_overrides/contract.py
> +        This function is largely copied from web3 ContractFunction with important addition.
"with" -> "with an"

2021-03-03 17:03 UTC, calina-c commented
@trentmc:
(a) not all, just the empty ones. I actually wanted to discuss with the team. An empty__init__.py is not required anymore to signal namespaces. (since Python 3.4, and we are using 3.8 on all repos). However, is there alternately something else that could break?
(b) added the initialise docstrings because Codacy was complaining about missing docstrings for __init__ function. Even if it's trivial just saying that it initialises the object, it's better to have one. i.e. for documentation generators, IDEs that plug into the docstrings etc. I'd rather add a few trivialities and encourage docstrings. Or we can work through the list and add more meaningful documentation.

2021-03-04 08:59 UTC, trentmc approved these changes

2021-03-04 09:31 UTC, calina-c commented
For extra safety reasons, on Samer's suggestions, I will run a local build to check the imports.

2021-03-04 10:15 UTC, calina-c commented
Seems ok. Imports work.

2021-03-04 11:33 UTC, merged