Strip JSON spaces for compute to data.
oceanprotocol/ocean.py pull request #257
Opened 2021-03-29 06:10 UTC by calina-c

Related to new changes in Provider. Not sure if it will pass yet, until the release of a new provider.

2021-03-29 07:37 UTC, calina-c commented
Blocked by Aquarius version.

2021-04-01 09:09 UTC, alexcos20 commented
we have v0.4.7, so it should be fine with that

2021-04-05 07:57 UTC, trentmc commented on .travis.yml
> -  - export PROVIDER_VERSION=ptalgs
This change doesn't seem to "strip JSON spaces", and there is no context to what it's for. 

Could you either update the PR description (and ensuing commit message) to give context, or put this in a different PR?

2021-04-05 07:57 UTC, trentmc commented on .travis.yml
> -  - export AQUARIUS_VERSION=v2.2.5
This change doesn't seem to "strip JSON spaces", and there is no context to what it's for. 

Could you either update the PR description (and ensuing commit message) to give context, or put this in a different PR?

2021-04-05 07:58 UTC, trentmc requested changes
Two of the changes don't "strip JSON spaces", and there is no context to what they are for. 

For each: please update the PR description (and ensuing commit message) to give context, or put it in a different PR.

2021-04-05 08:07 UTC, calina-c commented
@trentmc I updated the description. This was a problem because our Travis setup was hardcoded to some previous versions of aqua and provider, instead of testing with the Barge version. These were probably introduced during tests of some features in particular, and carried along into the main branch erroneously.

"Fixes provider and aquarius setup being hardcoded instead of used from Barge."

2021-04-05 08:26 UTC, trentmc approved these changes

2021-04-05 08:26 UTC, merged