Adds testing for service_agreements.
oceanprotocol/ocean.py pull request #303
Opened 2021-04-27 12:55 UTC by calina-c

Closes #292.

2021-04-28 08:49 UTC, calina-c commented
Added https://github.com/oceanprotocol/ocean.py/issues/306 as a possible follow-up.

2021-04-28 10:36 UTC, trentmc submitted a review, later dismissed
Did a cursory review, looks sane

2021-04-29 02:37 UTC, DMats requested changes
This PR removes 3 unused methods. I'm fine with this because it reduces maintenance and code bloat. However, it raises questions in my mind about API design cohesion across the Ocean Protocol tech stack. I'd love to discuss this topic further with the team at some point.

2021-04-29 10:57 UTC, calina-c commented on ocean_lib/common/aquarius/test/test_aquarius.py
> +
The intention was "test endpoints involving multiple ddos"

2021-04-29 10:58 UTC, calina-c commented on ocean_lib/common/aquarius/test/test_aquarius.py
> +    # TODO: make sure we need to remove datePublished.
That's my question, yes. @trentmc what do you think? Is it the expected behaviour that aqua returns a datePublished key, which is not present in the metadata sample?

2021-04-29 13:59 UTC, DMats commented on ocean_lib/common/aquarius/test/test_aquarius.py
> +
Oh lol.  Then I totally misunderstood.  Please update the test names to be more descriptive and perhaps add docstrings as well.

2021-04-29 15:02 UTC, DMats approved these changes

2021-04-29 18:04 UTC, DMats approved these changes

2021-04-29 18:05 UTC, merged