Issue 358 status flags
oceanprotocol/ocean.py pull request #361
Opened 2021-06-30 08:10 UTC by calina-c

Closes #358.

Leaving as Draft to clarify whether there should be a different error code on is_consumable. For now, I kept ASSET_DISABLED even for the retired and unlisted cases.

2021-07-01 19:04 UTC, DMats requested changes

2021-07-01 19:30 UTC, calina-c commented on ocean_lib/common/ddo/ddo.py
>              return ConsumableCodes.ASSET_DISABLED
I discussed this with Alex and he recommended using the same code (ASSET_DISABLED)

2021-07-01 19:38 UTC, DMats commented
Given my uncertainty about these changes, I've requested @alexcos20 review this PR.

2021-07-02 16:50 UTC, DMats commented
After talking it through with @calina-c I see why @alexcos20 advised not to check the `isListed` flag when determining the result of `is_consumable()`. The `is_consumable` flag determines whether an asset shown in the marketplace can be consumed (aka. whether the Download button appears or not). The `isListed` flag determines whether the asset shows up in the marketplace at all.  If an asset is not listed, then it doesn't matter what `is_consumable` returns.

2021-07-02 16:51 UTC, DMats approved these changes

2021-07-02 18:05 UTC, merged