Update example_config.py.
oceanprotocol/ocean.py pull request #427
Opened 2021-08-04 13:53 UTC by mariacarmina

Fixes #331  .

Changes proposed in this PR:

- added config support for ganache, ropsten, rinkeby, mainnet, polygon-mainnet and BSC;
- removed unnecessary uni test that worked only for ganache network from `test_config.py`;
- refactored `config_defaults` from `config.py` to be able to use it as a basic config structure.

2021-08-04 13:57 UTC, mariacarmina commented
As I saw in #393 should I also add the store intervals for each network as well, @DMats @calina-c @alexcos20 ?

2021-08-05 17:58 UTC, mariacarmina commented
I have created a draft refactor related to `example_config.py` that matches some discussed aspects. I missed to integrate the network name in the config dict, but as far as I saw the `network` key from the ocean.py config stands for the actual RPC, not for the network name itself. I fetched the chain id of that env var RPC and then I searched through the chain ids from `CONFIG_HELPER_NETWORKS` dict. I do not find useful in this situation the `network name`, since we search for the chain id. Even if in ocean.js the search is made through the network name, in ocean.py we provide different concepts for config object.

2021-08-06 04:12 UTC, DMats requested changes

2021-08-06 09:22 UTC, mariacarmina commented on ocean_lib/example_config.py
> +    3: {
I have tried before with `dict.update()`, but it modifies the object itself, not returning a new one and in the end all the networks will have the same config.

2021-08-06 12:46 UTC, mariacarmina commented
I have added the NETWORK_URL env var to `pytest.ini` and also to `tox.ini` (`127.0.0.1:8545` and also tested with `172.15.0.3:8545` which is present in the `barge` script) and some tests failed due to the fact that Aquarius could not fetch the created ddo from the unit tests like so 
![Screenshot from 2021-08-06 15-45-03](https://user-images.githubusercontent.com/50501033/128512354-829c606b-642d-4fd4-ad15-0d434dd31e69.png)
And I have seen other error messages such as `The did <did> is not in the OceanDB.`

2021-08-10 08:12 UTC, closed without merging