Dispenser flow README
oceanprotocol/ocean.py pull request #474
Opened 2021-09-02 13:42 UTC by mariacarmina

Fixes #461  .

Changes proposed in this PR:

- create a README which describes dispenser flow.

2021-09-06 08:01 UTC, calina-c requested changes

2021-09-06 08:01 UTC, calina-c commented on READMEs/dispenser-flow.md
> +data_token = ocean.create_data_token('DataToken1', 'DT1', alice_wallet, blob=ocean.config.metadata_cache_uri)
I would add an empty line before the data token instructions, to better separate the wallet and data token parts.

2021-09-06 08:01 UTC, calina-c commented on READMEs/dispenser-flow.md
> +```
can we add an assertion or print statement about this token, to make sure the dispense worked?

2021-09-06 13:59 UTC, mariacarmina commented
Successfully tested on `rinkeby` and I attach here the trace.
<details>
<summary> Dispenser flow - Success on Rinkeby </summary>
<p>
(venv) maria@maria-VirtualBox:~/Desktop/test3$ python <br/>
Python 3.8.10 (default, Jun  2 2021, 10:49:15) <br/>
[GCC 9.4.0] on linux<br/>
Type "help", "copyright", "credits" or "license" for more information.<br/>
>>> from ocean_lib.example_config import ExampleConfig<br/>
>>> from ocean_lib.ocean.ocean import Ocean<br/>
>>> config = ExampleConfig.get_config()<br/>
>>> ocean = Ocean(config)<br/>
>>> <br/>
>>> print(f"config.metadata_cache_uri = '{config.metadata_cache_uri}'")<br/>
config.metadata_cache_uri = 'https://aquarius.oceanprotocol.com'<br/>
>>> print(f"config.provider_url = '{config.provider_url}'")<br/>
config.provider_url = 'https://provider.rinkeby.oceanprotocol.com'<br/>
>>> <br/>
>>> #Alice's wallet<br/>
>>> import os<br/>
>>> from ocean_lib.web3_internal.wallet import Wallet<br/>
>>> alice_wallet = Wallet(ocean.web3, private_key=os.getenv('TEST_PRIVATE_KEY1'))<br/>
>>> print(f"alice_wallet.address = '{alice_wallet.address}'")<br/>
alice_wallet.address = '0xaa350D05F253a939Ec7fa5A4A8be522372d49b19'<br/>
>>> assert alice_wallet.web3.eth.get_balance(alice_wallet.address) > 0, "need ETH"<br/>
>>> data_token = ocean.create_data_token('DataToken1', 'DT1', alice_wallet, blob=ocean.config.metadata_cache_uri)<br/>
>>> token_address = data_token.address<br/>
>>> print(f"token_address = '{token_address}'")<br/>
token_address = '0xebFB9FdcC9f12E1a8076e67c168Ab13b37919fB5'<br/>
>>> from ocean_lib.web3_internal.contract_utils import get_contracts_addresses<br/>
>>> from ocean_lib.models.dispenser import DispenserContract<br/>
>>> from ocean_lib.web3_internal.currency import to_wei<br/>
>>> contracts_addresses = get_contracts_addresses('rinkeby', config.address_file)<br/>
>>> contracts_addresses<br/>
{'DTFactory': '0x3fd7A00106038Fb5c802c6d63fa7147Fe429E83a', 'BFactory': '0x53eDF9289B0898e1652Ce009AACf8D25fA9A42F8', 'FixedRateExchange': '0xeD1DfC5F3a589CfC4E8B91C1fbfC18FC6699Fbde', 'Metadata': '0xFD8a7b6297153397B7eb4356C47dbd381d58bFF4', 'Ocean': '0x8967BCF84170c91B0d24D4302C2376283b0B3a07', 'Dispenser': '0x623744Cd25Ed553d3b4722667697F926cf99658B', 'chainId': 4, 'startBlock': 7294090}<br/>
>>> dispenser_address = contracts_addresses["Dispenser"]<br/>
>>> dispenser = DispenserContract(alice_wallet.web3, dispenser_address)<br/>
>>> dispenser.activate(token_address, to_wei(100), to_wei(100), alice_wallet)<br/>
'0xa0bf099c25ea3904859ae4e8dcd340462f4d0743785b046baff1f35c38d951cd'<br/>
>>> assert dispenser.is_active(token_address), f"dispenser is not active for {token_address} data token."<br/>
>>> <br/>
>>> data_token.mint(dispenser_address, to_wei(100), alice_wallet)<br/>
'0xbf5e323b8f341a6d585c5d18bb2810ae286ea742e395e3295b539cc90fba316a'<br/>
>>> data_token.approve(dispenser_address, to_wei(100), alice_wallet)<br/>
'0xd1e70ff85d78aee3a3298572ea9789365925df4db013064e82c54b46dba1a930'<br/>
>>> tx_result = dispenser.dispense(token_address, to_wei(50), alice_wallet)<br/>
>>> assert tx_result, "failed to dispense data tokens for Alice."<br/>
>>> print(f"tx_result: '{tx_result}'")<br/>
tx_result: '0x8cc351fe0476d4939630e5703e9e1d661911d63543d3f11e7375992953f83b8e'<br/>

2021-09-07 08:40 UTC, calina-c submitted a review, later dismissed

2021-09-09 15:43 UTC, merged