Use provider address in pay for service.
oceanprotocol/ocean.py pull request #475
Opened 2021-09-06 12:49 UTC by calina-c

Closes #469.

2021-09-13 11:44 UTC, alexcos20 requested changes

2021-09-13 11:44 UTC, alexcos20 commented on READMEs/marketplace-flow.md
> +    service.get_provider_address()
this is wrong. It should be the C2d Address, and not the provider address

2021-09-13 11:44 UTC, alexcos20 commented on ocean_lib/models/test/test_order.py
> +            order[6] == sa.get_provider_address()
this is wrong. It should be the C2d Address, and not the provider address

2021-09-13 11:44 UTC, alexcos20 commented on tests/integration/test_compute_flow.py
> +    consumer = service.get_provider_address()
this is wrong. It should be the C2d Address, and not the provider address

2021-09-13 11:45 UTC, alexcos20 commented
Please add a test that starts a compute with dataset A publisher on provider 1, algo B published on provider 2

2021-09-14 05:15 UTC, calina-c commented
We already have this test as part of test_compute_multi_inputs.

And this morning, barge won't fund my accounts either, so I can't run any ocean.py tests (not even on main). I assume it's because I tried to run v4 last week and somehow messed up my addresses/artifacts. I'll continue to try debugging this.

2021-09-14 05:17 UTC, calina-c commented
<img width="939" alt="Screenshot 2021-07-26 at 14 06 35" src="https://user-images.githubusercontent.com/4101015/133199077-8a93ee47-6214-40ac-8b09-0624801a5987.png">

Barge has this error starting up, by the way...

2021-09-14 05:18 UTC, calina-c commented
<img width="1363" alt="Screenshot 2021-09-14 at 08 17 01" src="https://user-images.githubusercontent.com/4101015/133199126-b39f00d3-4040-41f0-b91a-703ca3bab455.png">

Barge had this startup error btw.

2021-09-14 07:29 UTC, calina-c commented
It seems the barge error was local and disappeared after pruning.

2021-09-21 06:57 UTC, alexcos20 approved these changes

2021-09-21 12:44 UTC, merged