Integrate provider asset_urls endpoint
oceanprotocol/ocean.py pull request #618
Opened 2022-01-03 15:18 UTC by maldo-ctrl

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>

Fixes #607  .

Changes proposed in this PR:

- Integrate asset_url endpoint in 
- 
-

2022-01-04 17:32 UTC, calina-c reviewed
Asked a small question. LGTM otherwise.

2022-01-04 19:46 UTC, DMats requested changes

2022-01-04 19:46 UTC, DMats commented on ocean_lib/data_provider/data_service_provider.py
> +            return False
This error returns `False`. but the error on line 846 returns `None`.  Please pick one error convention.

2022-01-04 19:46 UTC, DMats commented on ocean_lib/data_provider/data_service_provider.py
> +    ) -> None:
Once you've selected an error convention, update this return type hint.

```
Optional[dict]
```
or
```
Union[bool, dict]
```

2022-01-07 13:43 UTC, calina-c approved these changes
Good work! Did you merge v4main? Let me know if I can merge :)

2022-01-07 14:08 UTC, merged