Issue652 artifacts setup readmes
oceanprotocol/ocean.py pull request #685
Opened 2022-01-27 13:46 UTC by md0x

Fixes #652  .

Changes proposed in this PR:

- Remove `artifacts `folder
- Update readmes
- Update tox flow
- Add latest ocean tokens artifacts lib

2022-01-27 18:52 UTC, calina-c requested changes
This is perfect, except it's already time for version 1.0.0a17 :D
Please merge v4main, as well.

I assume you tested the setup and it works. For extra safety, can you delete and recreate your venv to make sure there are no previous artifacts left in there, and all new ones are from the contracts package?

2022-01-27 18:54 UTC, calina-c commented
Are there only 3 readmes to change?

2022-01-28 14:29 UTC, calina-c approved these changes

2022-01-28 15:44 UTC, DMats approved these changes

2022-01-28 15:48 UTC, merged