Disconnecting components
oceanprotocol/ocean.py pull request #785
Opened 2022-04-12 16:34 UTC by mariacarmina

Fixes oceanprotocol/multi-repo-issue#138.

Changes proposed in this PR:

- 
- 
-

2022-04-13 18:30 UTC, mariacarmina commented
I ran couple of tests with barge and then I have turned it off to see the behavior of pytest.
At the beginning, it froze couple of seconds and then it threw error log (for not finding the connection to the components).

![Screenshot from 2022-04-13 21-21-45](https://user-images.githubusercontent.com/50501033/163246052-d6bb6726-6858-4d99-ba27-28529c997d99.png)

After these errors occurred, I started again barge, but nothing seemed to re-establish and the tests were still failing. The problem is that pytest couldn't re-establish the connection with the other components after they were turned off couple of seconds.

2022-04-18 06:32 UTC, calina-c requested changes

2022-04-18 06:32 UTC, calina-c commented on bad-aqua-config.ini
> +[eth-network]
please move this somewhere under tests or a samples folder. This file does not belong in the main codebase.

2022-04-21 03:21 UTC, calina-c approved these changes

2022-04-21 09:01 UTC, merged