Addresses imported from the venv
oceanprotocol/ocean.py pull request #975
Opened 2022-09-30 13:53 UTC by mariacarmina

Fixes #971  .

Changes proposed in this PR:

- removed `--pre` flag from ocean-lib installation step
- fixed addresses import, updated address file path
- tested on rinkeby.

2022-09-30 13:55 UTC, mariacarmina commented
Test output:
![Screenshot from 2022-09-30 16-54-42](https://user-images.githubusercontent.com/50501033/193285436-4a35b665-9779-4d18-b6bd-aeb721794732.png)

It retrieved the addresses successfully.

2022-10-02 23:17 UTC, trentmc commented
This should work by default, not just if you use ExampleConfig. Putting it into ExampleConfig is too late.

Examples:
1. Anyone using ocean_lib for some remote network should be able to just specify the network RPC. From that, it should auto-find the chainid. From that, it should auto-find the addresses. If the user has to specific chainid or addresses, then we're still not done.
2.  You can capture the essence of (1) in the test_mumbai.py::test_ocean_tx. It should work, without having to specify the Ocean addresses anywhere. (And not by forcing it in some example config).

2022-10-04 05:25 UTC, calina-c commented
@mariacarmina please use the latest version of main.Then, keeping your `--pre` changes, I think adding the changes in get_contracts_addresses, like done for the CHAIN_ID, is a good way to go.

2022-10-05 08:46 UTC, mariacarmina commented
> 

Can we have some test keys on mumbai as we have exposed for ganache? In order to make `test_mumbai::test_ocean_tx` pass, we need to have remote test keys exported and I thought that maybe we can set them in `pytest.ini` file as well.

2022-10-05 09:02 UTC, trentmc commented
> @trentmc, can we have some test keys on mumbai as we have exposed for ganache? In order to make `test_mumbai::test_ocean_tx` pass, we need to have remote test keys exported and I thought that maybe we can set them in `pytest.ini` file as well.

We have test keys, but they cannot be publicly visible because bots will eat the fake MATIC, and you can only get a little fake MATIC at a time from faucets.

Our test keys are visible to CI as Github Actions Secrets. The CI can see them: the other Mumbai test needs fake MATIC and the tests pass.

You will need the keys locally too. Instructions are at :
https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/developers.md

2022-10-05 11:50 UTC, trentmc requested changes
You can *not* put those private keys into the code, because bots will see them and grab them.

I've already explained to you elsewhere today how they can access these private keys: using github Actions Secrets. The other Mumbai test uses these already. 

Even doing this commit to this branch likely compromises the keys. Now we will likely have to generate new ones :(

2022-10-06 06:02 UTC, calina-c commented on ocean_lib/example_config.py
> +        config_helper["ADDRESS_FILE"] = (
this shouldn't be in Example Config, it should be in `get_contracts_addresses`, similar to how we configure chain_id automatically when undefined.

2022-10-06 09:36 UTC, closed without merging