Updated README.
oceanprotocol/ocean.py pull request #992
Opened 2022-10-05 11:23 UTC by mariacarmina

Fixes #991  .

Changes proposed in this PR:

- updated python version in the simple flow README
- mentioned the issue for M1 type processors also in the simple flow README.

2022-10-05 11:46 UTC, trentmc requested changes
This is way too verbose. Figure out a way to make it a one-liner. If needed, link to a separate readme with details.

2022-10-06 05:59 UTC, calina-c commented on READMEs/data-nfts-and-datatokens-flow.md
> +For M1 processors, if the installation of ocean lib fails due to `coincurve` or
I would create a subsection or a different readme called "Known issues" and include a shortened version of this content. How about that? @trentmc @mariacarmina

2022-10-06 06:50 UTC, MBadea17 reviewed
Currently, there are two different sections of the installation of ocean-lib. One is in the main readme (https://github.com/oceanprotocol/ocean.py#-installation), the other one is in the simple flow (https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/data-nfts-and-datatokens-flow.md#install-the-library). Also, the descriptions are slightly different (one is in Python virtual environment, the other is without venv), which is confusing and adds friction. I would leave it in a single place - in the main read.me.

Agree with Calina to have a section for known issues.

2022-10-19 11:16 UTC, calina-c commented
Integrated in ocean brownie branch

2022-10-19 11:16 UTC, closed without merging